package org.cipher.ciphtypes.polygraphic;

import java.util.Arrays;
import java.util.Random;

/**
 *  The Running Key cipher has the same internal workings as the Vigenere cipher. The difference lies in
 *  how the key is chosen; the Vigenere cipher uses a short key that repeats, whereas the running key
 *  cipher uses a long key such as an excerpt from a book. This means the key does not repeat, making
 *  cryptanalysis more difficult. The cipher can still be broken though, as there are statistical patterns
 *  in both the key and the plaintext which can be exploited. If the key for the running key cipher comes
 *  from a statistically random source, then it becomes a 'one time pad' cipher. One time pads are
 *  theoretically unbreakable ciphers, because every possible decryption is equally likely.
 *
 *  Limit of autogenerated keyword is 60 to 5000
 *
 * @author Piotr 'pitrecki' Nowak
 * @version 1.0.0
 * Created by Pitrecki on 2016-12-17.
 * @see VinegereCipher
 */
public class RunningKeyCipher extends VinegereCipher
{
    private final int MAX_BOUND = 5000;

    public RunningKeyCipher() {
        super();
        setKeyword(keywordGenerator());
    }

    /**
     * This method generates a keyword in the range of from 60 to 5000
     * @return autogenerated keyword.
     */

    private String keywordGenerator() {
        //size between 60 and MAX_BOUND
        Character[] keywordArray = new Character[new Random().nextInt(MAX_BOUND)+60];
        for (int i = 0; i < keywordArray.length; i++) {
            int randomCharacter = new Random().nextInt(ASCII_TABLE.length);
            keywordArray[i] = ASCII_TABLE[randomCharacter];
        }

        return Arrays.toString(keywordArray).replaceAll("[\\[\\], ]","");
    }

    @Override
    public String prepareDataToPrint() {
        return "GENERATED KEYWORD: " + getKeyword()
                +"\n" + getProcessedText();
    }
}
